### ISSUE TITLE
Profil korisnika

### ISSUE THREAD

**Issue by predragfalcic** [predragfalcic/BSEP#1]
Kada korisnik kreira account i uloguje se na sistem, potrebno je da bude prosledjen na svoju profilnu stranicu sa koje, u zavisnosti od svoje uloge moze da pregleda entitete iz baze. Za sada se korisnik prosledjuje na stranicu koja ne postoji.

**Comment by milosavljevic94** [comment]
Profil korisnika za sada nije potreban, vec bi pri uspesnom logovanju mogla da se prosledi neka home stranica na kojoj ce se prikazivati logovi i moci izvrsiti njihova pretraga.
